name: health check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-nameless-feather-5726.fly.dev/health
          max-attempts: 3
          retry-delay: 5s